function(check_cpu)
    try_run(RUN_RESULT COMPILE_RESULT
            SOURCES ${CMAKE_CURRENT_FUNCTION_LIST_DIR}/CpuChecker.c
            COMPILE_OUTPUT_VARIABLE COMPILE_OUT
            RUN_OUTPUT_STDOUT_VARIABLE STD_OUT
    )
    if (COMPILE_RESULT)
        message(STATUS "Cpu Checker Result: ")
        message(STATUS ${STD_OUT})

        string(REGEX MATCH "SSE3:\t*(yes|no)" REGEX_VALUE ${STD_OUT})
        set(SSE3_SUPPORT ${CMAKE_MATCH_1} PARENT_SCOPE)

        string(REGEX MATCH "SSSE3:\t(yes|no)" REGEX_VALUE ${STD_OUT})
        set(SSSE3_SUPPORT ${CMAKE_MATCH_1} PARENT_SCOPE)

        string(REGEX MATCH "FMA:\t(yes|no)" REGEX_VALUE ${STD_OUT})
        set(FMA_SUPPORT ${CMAKE_MATCH_1} PARENT_SCOPE)

        string(REGEX MATCH "SSE4.1:\t(yes|no)" REGEX_VALUE ${STD_OUT})
        set(SSE4_1_SUPPORT ${CMAKE_MATCH_1} PARENT_SCOPE)

        string(REGEX MATCH "SSE4.2:\t(yes|no)" REGEX_VALUE ${STD_OUT})
        set(SSE4_2_SUPPORT ${CMAKE_MATCH_1} PARENT_SCOPE)

        string(REGEX MATCH "AVX:\t(yes|no)" REGEX_VALUE ${STD_OUT})
        set(AVX_SUPPORT ${CMAKE_MATCH_1} PARENT_SCOPE)

        string(REGEX MATCH "MMX:\t(yes|no)" REGEX_VALUE ${STD_OUT})
        set(MMX_SUPPORT ${CMAKE_MATCH_1} PARENT_SCOPE)

        string(REGEX MATCH "SSE:\t(yes|no)" REGEX_VALUE ${STD_OUT})
        set(SSE_SUPPORT ${CMAKE_MATCH_1} PARENT_SCOPE)

        string(REGEX MATCH "SSE2:\t(yes|no)" REGEX_VALUE ${STD_OUT})
        set(SSE2_SUPPORT ${CMAKE_MATCH_1} PARENT_SCOPE)

        string(REGEX MATCH "AVX2:\t(yes|no)" REGEX_VALUE ${STD_OUT})
        set(AVX2_SUPPORT ${CMAKE_MATCH_1} PARENT_SCOPE)

        string(REGEX MATCH "AVX512:\t(yes|no)" REGEX_VALUE ${STD_OUT})
        set(AVX512_SUPPORT ${CMAKE_MATCH_1} PARENT_SCOPE)

        string(REGEX MATCH "CACHE:\t([0-9]*)" REGEX_VALUE ${STD_OUT})
        set(CACHE_LINE_SIZE ${CMAKE_MATCH_1} PARENT_SCOPE)

    else ()
        message(FATAL_ERROR "Error while early compiling SimdChecker: " ${COMPILE_OUT})

    endif ()

endfunction()

function(huh_target_simd_compiler_flags Target Visibility)
    include(CompilerHelper)
    if (SSE_SUPPORT)
        huh_target_compile_options(${Target} ${Visibility} GCClang -msse Intel /QxSSE MSVC /arch:SSE)
    endif ()
    if (SSE2_SUPPORT)
        huh_target_compile_options(${Target} ${Visibility} GCClang -msse2 Intel /QxSSE2 MSVC /arch:SSE2)
    endif ()
    if (SSE3_SUPPORT)
        huh_target_compile_options(${Target} ${Visibility} GCClang -msse3 Intel /QxSSE3)
    endif ()
    if (SSSE3_SUPPORT)
        huh_target_compile_options(${Target} ${Visibility} GCClang -mssse3 Intel /QxSSSE3)
    endif ()
    if (SSE4_1_SUPPORT)
        huh_target_compile_options(${Target} ${Visibility} GCClang -msse4.1 Intel /QxSSE4.1)
    endif ()
    if (SSE4_2_SUPPORT)
        huh_target_compile_options(${Target} ${Visibility} GCClang -msse4.2 Intel /QxSSE4.2)
    endif ()
    if (AVX_SUPPORT)
        huh_target_compile_options(${Target} ${Visibility} GCClang -mavx Intel /QxAVX MSVC /arch:AVX)
    endif ()
    if (AVX2_SUPPORT)
        huh_target_compile_options(${Target} ${Visibility} GCClang -mavx2 Intel /QxAVX2 MSVC /arch:AVX2)
        if (FMA_SUPPORT)
            huh_target_compile_options(${Target} ${Visibility} GCClang -mfma)
        endif ()
    endif ()
endfunction()

function(huh_target_simd_definitions Target Visibility)
    if (SSE_SUPPORT)
        target_compile_definitions(${Target} ${Visibility} HUH_SSE_SUPPORT)
    endif ()
    if (SSE2_SUPPORT)
        target_compile_definitions(${Target} ${Visibility} HUH_SSE2_SUPPORT)
    endif ()
    if (SSE3_SUPPORT)
        target_compile_definitions(${Target} ${Visibility} HUH_SSE3_SUPPORT)
    endif ()
    if (SSSE3_SUPPORT)
        target_compile_definitions(${Target} ${Visibility} HUH_SSSE3_SUPPORT)
    endif ()
    if (SSE4_1_SUPPORT)
        target_compile_definitions(${Target} ${Visibility} HUH_SSE4_1_SUPPORT)
    endif ()
    if (SSE4_2_SUPPORT)
        target_compile_definitions(${Target} ${Visibility} HUH_SSE4_2_SUPPORT)
    endif ()
    if (AVX_SUPPORT)
        target_compile_definitions(${Target} ${Visibility} HUH_AVX_SUPPORT)
    endif ()
    if (AVX2_SUPPORT)
        target_compile_definitions(${Target} ${Visibility} HUH_AVX2_SUPPORT)
    endif ()
    if (FMA_SUPPORT)
        target_compile_definitions(${Target} ${Visibility} HUH_FMA_SUPPORT)
    endif ()
    if (CACHE_LINE_SIZE)
        target_compile_definitions(${Target} ${Visibility} HUH_CACHE_LINE_SIZE=${CACHE_LINE_SIZE})
    endif ()
endfunction()
