#include <HUH/Cuda/definitions.h>

namespace HUH {
std::string ToString(cudaError_t err) {
    switch (err) {
        case cudaSuccess:
            return "cudaSuccess";
        case cudaErrorInvalidValue:
            return "cudaErrorInvalidValue";
        case cudaErrorMemoryAllocation:
            return "cudaErrorMemoryAllocation";
        case cudaErrorInitializationError:
            return "cudaErrorInitializationError";
        case cudaErrorCudartUnloading:
            return "cudaErrorCudartUnloading";
        case cudaErrorProfilerDisabled:
            return "cudaErrorProfilerDisabled";
        case cudaErrorProfilerNotInitialized:
            return "cudaErrorProfilerNotInitialized";
        case cudaErrorProfilerAlreadyStarted:
            return "cudaErrorProfilerAlreadyStarted";
        case cudaErrorProfilerAlreadyStopped:
            return "cudaErrorProfilerAlreadyStopped";
        case cudaErrorInvalidConfiguration:
            return "cudaErrorInvalidConfiguration";
        case cudaErrorVersionTranslation:
            return "cudaErrorVersionTranslation";
        case cudaErrorInvalidPitchValue:
            return "cudaErrorInvalidPitchValue";
        case cudaErrorInvalidSymbol:
            return "cudaErrorInvalidSymbol";
        case cudaErrorInvalidHostPointer:
            return "cudaErrorInvalidHostPointer";
        case cudaErrorInvalidDevicePointer:
            return "cudaErrorInvalidDevicePointer";
        case cudaErrorInvalidTexture:
            return "cudaErrorInvalidTexture";
        case cudaErrorInvalidTextureBinding:
            return "cudaErrorInvalidTextureBinding";
        case cudaErrorInvalidChannelDescriptor:
            return "cudaErrorInvalidChannelDescriptor";
        case cudaErrorInvalidMemcpyDirection:
            return "cudaErrorInvalidMemcpyDirection";
        case cudaErrorAddressOfConstant:
            return "cudaErrorAddressOfConstant";
        case cudaErrorTextureFetchFailed:
            return "cudaErrorTextureFetchFailed";
        case cudaErrorTextureNotBound:
            return "cudaErrorTextureNotBound";
        case cudaErrorSynchronizationError:
            return "cudaErrorSynchronizationError";
        case cudaErrorInvalidFilterSetting:
            return "cudaErrorInvalidFilterSetting";
        case cudaErrorInvalidNormSetting:
            return "cudaErrorInvalidNormSetting";
        case cudaErrorMixedDeviceExecution:
            return "cudaErrorMixedDeviceExecution";
        case cudaErrorNotYetImplemented:
            return "cudaErrorNotYetImplemented";
        case cudaErrorMemoryValueTooLarge:
            return "cudaErrorMemoryValueTooLarge";
        case cudaErrorStubLibrary:
            return "cudaErrorStubLibrary";
        case cudaErrorInsufficientDriver:
            return "cudaErrorInsufficientDriver";
        case cudaErrorCallRequiresNewerDriver:
            return "cudaErrorCallRequiresNewerDriver";
        case cudaErrorInvalidSurface:
            return "cudaErrorInvalidSurface";
        case cudaErrorDuplicateVariableName:
            return "cudaErrorDuplicateVariableName";
        case cudaErrorDuplicateTextureName:
            return "cudaErrorDuplicateTextureName";
        case cudaErrorDuplicateSurfaceName:
            return "cudaErrorDuplicateSurfaceName";
        case cudaErrorDevicesUnavailable:
            return "cudaErrorDevicesUnavailable";
        case cudaErrorIncompatibleDriverContext:
            return "cudaErrorIncompatibleDriverContext";
        case cudaErrorMissingConfiguration:
            return "cudaErrorMissingConfiguration";
        case cudaErrorPriorLaunchFailure:
            return "cudaErrorPriorLaunchFailure";
        case cudaErrorLaunchMaxDepthExceeded:
            return "cudaErrorLaunchMaxDepthExceeded";
        case cudaErrorLaunchFileScopedTex:
            return "cudaErrorLaunchFileScopedTex";
        case cudaErrorLaunchFileScopedSurf:
            return "cudaErrorLaunchFileScopedSurf";
        case cudaErrorSyncDepthExceeded:
            return "cudaErrorSyncDepthExceeded";
        case cudaErrorLaunchPendingCountExceeded:
            return "cudaErrorLaunchPendingCountExceeded";
        case cudaErrorInvalidDeviceFunction:
            return "cudaErrorInvalidDeviceFunction";
        case cudaErrorNoDevice:
            return "cudaErrorNoDevice";
        case cudaErrorInvalidDevice:
            return "cudaErrorInvalidDevice";
        case cudaErrorDeviceNotLicensed:
            return "cudaErrorDeviceNotLicensed";
        case cudaErrorSoftwareValidityNotEstablished:
            return "cudaErrorSoftwareValidityNotEstablished";
        case cudaErrorStartupFailure:
            return "cudaErrorStartupFailure";
        case cudaErrorInvalidKernelImage:
            return "cudaErrorInvalidKernelImage";
        case cudaErrorDeviceUninitialized:
            return "cudaErrorDeviceUninitialized";
        case cudaErrorMapBufferObjectFailed:
            return "cudaErrorMapBufferObjectFailed";
        case cudaErrorUnmapBufferObjectFailed:
            return "cudaErrorUnmapBufferObjectFailed";
        case cudaErrorArrayIsMapped:
            return "cudaErrorArrayIsMapped";
        case cudaErrorAlreadyMapped:
            return "cudaErrorAlreadyMapped";
        case cudaErrorNoKernelImageForDevice:
            return "cudaErrorNoKernelImageForDevice";
        case cudaErrorAlreadyAcquired:
            return "cudaErrorAlreadyAcquired";
        case cudaErrorNotMapped:
            return "cudaErrorNotMapped";
        case cudaErrorNotMappedAsArray:
            return "cudaErrorNotMappedAsArray";
        case cudaErrorNotMappedAsPointer:
            return "cudaErrorNotMappedAsPointer";
        case cudaErrorECCUncorrectable:
            return "cudaErrorECCUncorrectable";
        case cudaErrorUnsupportedLimit:
            return "cudaErrorUnsupportedLimit";
        case cudaErrorDeviceAlreadyInUse:
            return "cudaErrorDeviceAlreadyInUse";
        case cudaErrorPeerAccessUnsupported:
            return "cudaErrorPeerAccessUnsupported";
        case cudaErrorInvalidPtx:
            return "cudaErrorInvalidPtx";
        case cudaErrorInvalidGraphicsContext:
            return "cudaErrorInvalidGraphicsContext";
        case cudaErrorNvlinkUncorrectable:
            return "cudaErrorNvlinkUncorrectable";
        case cudaErrorJitCompilerNotFound:
            return "cudaErrorJitCompilerNotFound";
        case cudaErrorUnsupportedPtxVersion:
            return "cudaErrorUnsupportedPtxVersion";
        case cudaErrorJitCompilationDisabled:
            return "cudaErrorJitCompilationDisabled";
        case cudaErrorUnsupportedExecAffinity:
            return "cudaErrorUnsupportedExecAffinity";
        case cudaErrorUnsupportedDevSideSync:
            return "cudaErrorUnsupportedDevSideSync";
        case cudaErrorContained:
            return "cudaErrorContained";
        case cudaErrorInvalidSource:
            return "cudaErrorInvalidSource";
        case cudaErrorFileNotFound:
            return "cudaErrorFileNotFound";
        case cudaErrorSharedObjectSymbolNotFound:
            return "cudaErrorSharedObjectSymbolNotFound";
        case cudaErrorSharedObjectInitFailed:
            return "cudaErrorSharedObjectInitFailed";
        case cudaErrorOperatingSystem:
            return "cudaErrorOperatingSystem";
        case cudaErrorInvalidResourceHandle:
            return "cudaErrorInvalidResourceHandle";
        case cudaErrorIllegalState:
            return "cudaErrorIllegalState";
        case cudaErrorLossyQuery:
            return "cudaErrorLossyQuery";
        case cudaErrorSymbolNotFound:
            return "cudaErrorSymbolNotFound";
        case cudaErrorNotReady:
            return "cudaErrorNotReady";
        case cudaErrorIllegalAddress:
            return "cudaErrorIllegalAddress";
        case cudaErrorLaunchOutOfResources:
            return "cudaErrorLaunchOutOfResources";
        case cudaErrorLaunchTimeout:
            return "cudaErrorLaunchTimeout";
        case cudaErrorLaunchIncompatibleTexturing:
            return "cudaErrorLaunchIncompatibleTexturing";
        case cudaErrorPeerAccessAlreadyEnabled:
            return "cudaErrorPeerAccessAlreadyEnabled";
        case cudaErrorPeerAccessNotEnabled:
            return "cudaErrorPeerAccessNotEnabled";
        case cudaErrorSetOnActiveProcess:
            return "cudaErrorSetOnActiveProcess";
        case cudaErrorContextIsDestroyed:
            return "cudaErrorContextIsDestroyed";
        case cudaErrorAssert:
            return "cudaErrorAssert";
        case cudaErrorTooManyPeers:
            return "cudaErrorTooManyPeers";
        case cudaErrorHostMemoryAlreadyRegistered:
            return "cudaErrorHostMemoryAlreadyRegistered";
        case cudaErrorHostMemoryNotRegistered:
            return "cudaErrorHostMemoryNotRegistered";
        case cudaErrorHardwareStackError:
            return "cudaErrorHardwareStackError";
        case cudaErrorIllegalInstruction:
            return "cudaErrorIllegalInstruction";
        case cudaErrorMisalignedAddress:
            return "cudaErrorMisalignedAddress";
        case cudaErrorInvalidAddressSpace:
            return "cudaErrorInvalidAddressSpace";
        case cudaErrorInvalidPc:
            return "cudaErrorInvalidPc";
        case cudaErrorLaunchFailure:
            return "cudaErrorLaunchFailure";
        case cudaErrorCooperativeLaunchTooLarge:
            return "cudaErrorCooperativeLaunchTooLarge";
        case cudaErrorTensorMemoryLeak:
            return "cudaErrorTensorMemoryLeak";
        case cudaErrorNotPermitted:
            return "cudaErrorNotPermitted";
        case cudaErrorNotSupported:
            return "cudaErrorNotSupported";
        case cudaErrorSystemNotReady:
            return "cudaErrorSystemNotReady";
        case cudaErrorSystemDriverMismatch:
            return "cudaErrorSystemDriverMismatch";
        case cudaErrorCompatNotSupportedOnDevice:
            return "cudaErrorCompatNotSupportedOnDevice";
        case cudaErrorMpsConnectionFailed:
            return "cudaErrorMpsConnectionFailed";
        case cudaErrorMpsRpcFailure:
            return "cudaErrorMpsRpcFailure";
        case cudaErrorMpsServerNotReady:
            return "cudaErrorMpsServerNotReady";
        case cudaErrorMpsMaxClientsReached:
            return "cudaErrorMpsMaxClientsReached";
        case cudaErrorMpsMaxConnectionsReached:
            return "cudaErrorMpsMaxConnectionsReached";
        case cudaErrorMpsClientTerminated:
            return "cudaErrorMpsClientTerminated";
        case cudaErrorCdpNotSupported:
            return "cudaErrorCdpNotSupported";
        case cudaErrorCdpVersionMismatch:
            return "cudaErrorCdpVersionMismatch";
        case cudaErrorStreamCaptureUnsupported:
            return "cudaErrorStreamCaptureUnsupported";
        case cudaErrorStreamCaptureInvalidated:
            return "cudaErrorStreamCaptureInvalidated";
        case cudaErrorStreamCaptureMerge:
            return "cudaErrorStreamCaptureMerge";
        case cudaErrorStreamCaptureUnmatched:
            return "cudaErrorStreamCaptureUnmatched";
        case cudaErrorStreamCaptureUnjoined:
            return "cudaErrorStreamCaptureUnjoined";
        case cudaErrorStreamCaptureIsolation:
            return "cudaErrorStreamCaptureIsolation";
        case cudaErrorStreamCaptureImplicit:
            return "cudaErrorStreamCaptureImplicit";
        case cudaErrorCapturedEvent:
            return "cudaErrorCapturedEvent";
        case cudaErrorStreamCaptureWrongThread:
            return "cudaErrorStreamCaptureWrongThread";
        case cudaErrorTimeout:
            return "cudaErrorTimeout";
        case cudaErrorGraphExecUpdateFailure:
            return "cudaErrorGraphExecUpdateFailure";
        case cudaErrorExternalDevice:
            return "cudaErrorExternalDevice";
        case cudaErrorInvalidClusterSize:
            return "cudaErrorInvalidClusterSize";
        case cudaErrorFunctionNotLoaded:
            return "cudaErrorFunctionNotLoaded";
        case cudaErrorInvalidResourceType:
            return "cudaErrorInvalidResourceType";
        case cudaErrorInvalidResourceConfiguration:
            return "cudaErrorInvalidResourceConfiguration";
        case cudaErrorStreamDetached:
            return "cudaErrorStreamDetached";
        case cudaErrorGraphRecaptureFailure:
            return "cudaErrorGraphRecaptureFailure";
        case cudaErrorUnknown:
            return "cudaErrorUnknown";
        case cudaErrorApiFailureBase:
            return "cudaErrorApiFailureBase";
        default:
            return "Unknown error";
    }
}

std::string ToString(CUresult err) {
    switch (err) {
        case CUDA_SUCCESS:
            return "CUDA_SUCCESS";
        case CUDA_ERROR_INVALID_VALUE:
            return "CUDA_ERROR_INVALID_VALUE";
        case CUDA_ERROR_OUT_OF_MEMORY:
            return "CUDA_ERROR_OUT_OF_MEMORY";
        case CUDA_ERROR_NOT_INITIALIZED:
            return "CUDA_ERROR_NOT_INITIALIZED";
        case CUDA_ERROR_DEINITIALIZED:
            return "CUDA_ERROR_DEINITIALIZED";
        case CUDA_ERROR_PROFILER_DISABLED:
            return "CUDA_ERROR_PROFILER_DISABLED";
        case CUDA_ERROR_PROFILER_NOT_INITIALIZED:
            return "CUDA_ERROR_PROFILER_NOT_INITIALIZED";
        case CUDA_ERROR_PROFILER_ALREADY_STARTED:
            return "CUDA_ERROR_PROFILER_ALREADY_STARTED";
        case CUDA_ERROR_PROFILER_ALREADY_STOPPED:
            return "CUDA_ERROR_PROFILER_ALREADY_STOPPED";
        case CUDA_ERROR_STUB_LIBRARY:
            return "CUDA_ERROR_STUB_LIBRARY";
        case CUDA_ERROR_CALL_REQUIRES_NEWER_DRIVER:
            return "CUDA_ERROR_CALL_REQUIRES_NEWER_DRIVER";
        case CUDA_ERROR_DEVICE_UNAVAILABLE:
            return "CUDA_ERROR_DEVICE_UNAVAILABLE";
        case CUDA_ERROR_NO_DEVICE:
            return "CUDA_ERROR_NO_DEVICE";
        case CUDA_ERROR_INVALID_DEVICE:
            return "CUDA_ERROR_INVALID_DEVICE";
        case CUDA_ERROR_DEVICE_NOT_LICENSED:
            return "CUDA_ERROR_DEVICE_NOT_LICENSED";
        case CUDA_ERROR_INVALID_IMAGE:
            return "CUDA_ERROR_INVALID_IMAGE";
        case CUDA_ERROR_INVALID_CONTEXT:
            return "CUDA_ERROR_INVALID_CONTEXT";
        case CUDA_ERROR_CONTEXT_ALREADY_CURRENT:
            return "CUDA_ERROR_CONTEXT_ALREADY_CURRENT";
        case CUDA_ERROR_MAP_FAILED:
            return "CUDA_ERROR_MAP_FAILED";
        case CUDA_ERROR_UNMAP_FAILED:
            return "CUDA_ERROR_UNMAP_FAILED";
        case CUDA_ERROR_ARRAY_IS_MAPPED:
            return "CUDA_ERROR_ARRAY_IS_MAPPED";
        case CUDA_ERROR_ALREADY_MAPPED:
            return "CUDA_ERROR_ALREADY_MAPPED";
        case CUDA_ERROR_NO_BINARY_FOR_GPU:
            return "CUDA_ERROR_NO_BINARY_FOR_GPU";
        case CUDA_ERROR_ALREADY_ACQUIRED:
            return "CUDA_ERROR_ALREADY_ACQUIRED";
        case CUDA_ERROR_NOT_MAPPED:
            return "CUDA_ERROR_NOT_MAPPED";
        case CUDA_ERROR_NOT_MAPPED_AS_ARRAY:
            return "CUDA_ERROR_NOT_MAPPED_AS_ARRAY";
        case CUDA_ERROR_NOT_MAPPED_AS_POINTER:
            return "CUDA_ERROR_NOT_MAPPED_AS_POINTER";
        case CUDA_ERROR_ECC_UNCORRECTABLE:
            return "CUDA_ERROR_ECC_UNCORRECTABLE";
        case CUDA_ERROR_UNSUPPORTED_LIMIT:
            return "CUDA_ERROR_UNSUPPORTED_LIMIT";
        case CUDA_ERROR_CONTEXT_ALREADY_IN_USE:
            return "CUDA_ERROR_CONTEXT_ALREADY_IN_USE";
        case CUDA_ERROR_PEER_ACCESS_UNSUPPORTED:
            return "CUDA_ERROR_PEER_ACCESS_UNSUPPORTED";
        case CUDA_ERROR_INVALID_PTX:
            return "CUDA_ERROR_INVALID_PTX";
        case CUDA_ERROR_INVALID_GRAPHICS_CONTEXT:
            return "CUDA_ERROR_INVALID_GRAPHICS_CONTEXT";
        case CUDA_ERROR_NVLINK_UNCORRECTABLE:
            return "CUDA_ERROR_NVLINK_UNCORRECTABLE";
        case CUDA_ERROR_JIT_COMPILER_NOT_FOUND:
            return "CUDA_ERROR_JIT_COMPILER_NOT_FOUND";
        case CUDA_ERROR_UNSUPPORTED_PTX_VERSION:
            return "CUDA_ERROR_UNSUPPORTED_PTX_VERSION";
        case CUDA_ERROR_JIT_COMPILATION_DISABLED:
            return "CUDA_ERROR_JIT_COMPILATION_DISABLED";
        case CUDA_ERROR_UNSUPPORTED_EXEC_AFFINITY:
            return "CUDA_ERROR_UNSUPPORTED_EXEC_AFFINITY";
        case CUDA_ERROR_UNSUPPORTED_DEVSIDE_SYNC:
            return "CUDA_ERROR_UNSUPPORTED_DEVSIDE_SYNC";
        case CUDA_ERROR_CONTAINED:
            return "CUDA_ERROR_CONTAINED";
        case CUDA_ERROR_INVALID_SOURCE:
            return "CUDA_ERROR_INVALID_SOURCE";
        case CUDA_ERROR_FILE_NOT_FOUND:
            return "CUDA_ERROR_FILE_NOT_FOUND";
        case CUDA_ERROR_SHARED_OBJECT_SYMBOL_NOT_FOUND:
            return "CUDA_ERROR_SHARED_OBJECT_SYMBOL_NOT_FOUND";
        case CUDA_ERROR_SHARED_OBJECT_INIT_FAILED:
            return "CUDA_ERROR_SHARED_OBJECT_INIT_FAILED";
        case CUDA_ERROR_OPERATING_SYSTEM:
            return "CUDA_ERROR_OPERATING_SYSTEM";
        case CUDA_ERROR_INVALID_HANDLE:
            return "CUDA_ERROR_INVALID_HANDLE";
        case CUDA_ERROR_ILLEGAL_STATE:
            return "CUDA_ERROR_ILLEGAL_STATE";
        case CUDA_ERROR_LOSSY_QUERY:
            return "CUDA_ERROR_LOSSY_QUERY";
        case CUDA_ERROR_NOT_FOUND:
            return "CUDA_ERROR_NOT_FOUND";
        case CUDA_ERROR_NOT_READY:
            return "CUDA_ERROR_NOT_READY";
        case CUDA_ERROR_ILLEGAL_ADDRESS:
            return "CUDA_ERROR_ILLEGAL_ADDRESS";
        case CUDA_ERROR_LAUNCH_OUT_OF_RESOURCES:
            return "CUDA_ERROR_LAUNCH_OUT_OF_RESOURCES";
        case CUDA_ERROR_LAUNCH_TIMEOUT:
            return "CUDA_ERROR_LAUNCH_TIMEOUT";
        case CUDA_ERROR_LAUNCH_INCOMPATIBLE_TEXTURING:
            return "CUDA_ERROR_LAUNCH_INCOMPATIBLE_TEXTURING";
        case CUDA_ERROR_PEER_ACCESS_ALREADY_ENABLED:
            return "CUDA_ERROR_PEER_ACCESS_ALREADY_ENABLED";
        case CUDA_ERROR_PEER_ACCESS_NOT_ENABLED:
            return "CUDA_ERROR_PEER_ACCESS_NOT_ENABLED";
        case CUDA_ERROR_PRIMARY_CONTEXT_ACTIVE:
            return "CUDA_ERROR_PRIMARY_CONTEXT_ACTIVE";
        case CUDA_ERROR_CONTEXT_IS_DESTROYED:
            return "CUDA_ERROR_CONTEXT_IS_DESTROYED";
        case CUDA_ERROR_ASSERT:
            return "CUDA_ERROR_ASSERT";
        case CUDA_ERROR_TOO_MANY_PEERS:
            return "CUDA_ERROR_TOO_MANY_PEERS";
        case CUDA_ERROR_HOST_MEMORY_ALREADY_REGISTERED:
            return "CUDA_ERROR_HOST_MEMORY_ALREADY_REGISTERED";
        case CUDA_ERROR_HOST_MEMORY_NOT_REGISTERED:
            return "CUDA_ERROR_HOST_MEMORY_NOT_REGISTERED";
        case CUDA_ERROR_HARDWARE_STACK_ERROR:
            return "CUDA_ERROR_HARDWARE_STACK_ERROR";
        case CUDA_ERROR_ILLEGAL_INSTRUCTION:
            return "CUDA_ERROR_ILLEGAL_INSTRUCTION";
        case CUDA_ERROR_MISALIGNED_ADDRESS:
            return "CUDA_ERROR_MISALIGNED_ADDRESS";
        case CUDA_ERROR_INVALID_ADDRESS_SPACE:
            return "CUDA_ERROR_INVALID_ADDRESS_SPACE";
        case CUDA_ERROR_INVALID_PC:
            return "CUDA_ERROR_INVALID_PC";
        case CUDA_ERROR_LAUNCH_FAILED:
            return "CUDA_ERROR_LAUNCH_FAILED";
        case CUDA_ERROR_COOPERATIVE_LAUNCH_TOO_LARGE:
            return "CUDA_ERROR_COOPERATIVE_LAUNCH_TOO_LARGE";
        case CUDA_ERROR_TENSOR_MEMORY_LEAK:
            return "CUDA_ERROR_TENSOR_MEMORY_LEAK";
        case CUDA_ERROR_NOT_PERMITTED:
            return "CUDA_ERROR_NOT_PERMITTED";
        case CUDA_ERROR_NOT_SUPPORTED:
            return "CUDA_ERROR_NOT_SUPPORTED";
        case CUDA_ERROR_SYSTEM_NOT_READY:
            return "CUDA_ERROR_SYSTEM_NOT_READY";
        case CUDA_ERROR_SYSTEM_DRIVER_MISMATCH:
            return "CUDA_ERROR_SYSTEM_DRIVER_MISMATCH";
        case CUDA_ERROR_COMPAT_NOT_SUPPORTED_ON_DEVICE:
            return "CUDA_ERROR_COMPAT_NOT_SUPPORTED_ON_DEVICE";
        case CUDA_ERROR_MPS_CONNECTION_FAILED:
            return "CUDA_ERROR_MPS_CONNECTION_FAILED";
        case CUDA_ERROR_MPS_RPC_FAILURE:
            return "CUDA_ERROR_MPS_RPC_FAILURE";
        case CUDA_ERROR_MPS_SERVER_NOT_READY:
            return "CUDA_ERROR_MPS_SERVER_NOT_READY";
        case CUDA_ERROR_MPS_MAX_CLIENTS_REACHED:
            return "CUDA_ERROR_MPS_MAX_CLIENTS_REACHED";
        case CUDA_ERROR_MPS_MAX_CONNECTIONS_REACHED:
            return "CUDA_ERROR_MPS_MAX_CONNECTIONS_REACHED";
        case CUDA_ERROR_MPS_CLIENT_TERMINATED:
            return "CUDA_ERROR_MPS_CLIENT_TERMINATED";
        case CUDA_ERROR_CDP_NOT_SUPPORTED:
            return "CUDA_ERROR_CDP_NOT_SUPPORTED";
        case CUDA_ERROR_CDP_VERSION_MISMATCH:
            return "CUDA_ERROR_CDP_VERSION_MISMATCH";
        case CUDA_ERROR_STREAM_CAPTURE_UNSUPPORTED:
            return "CUDA_ERROR_STREAM_CAPTURE_UNSUPPORTED";
        case CUDA_ERROR_STREAM_CAPTURE_INVALIDATED:
            return "CUDA_ERROR_STREAM_CAPTURE_INVALIDATED";
        case CUDA_ERROR_STREAM_CAPTURE_MERGE:
            return "CUDA_ERROR_STREAM_CAPTURE_MERGE";
        case CUDA_ERROR_STREAM_CAPTURE_UNMATCHED:
            return "CUDA_ERROR_STREAM_CAPTURE_UNMATCHED";
        case CUDA_ERROR_STREAM_CAPTURE_UNJOINED:
            return "CUDA_ERROR_STREAM_CAPTURE_UNJOINED";
        case CUDA_ERROR_STREAM_CAPTURE_ISOLATION:
            return "CUDA_ERROR_STREAM_CAPTURE_ISOLATION";
        case CUDA_ERROR_STREAM_CAPTURE_IMPLICIT:
            return "CUDA_ERROR_STREAM_CAPTURE_IMPLICIT";
        case CUDA_ERROR_CAPTURED_EVENT:
            return "CUDA_ERROR_CAPTURED_EVENT";
        case CUDA_ERROR_STREAM_CAPTURE_WRONG_THREAD:
            return "CUDA_ERROR_STREAM_CAPTURE_WRONG_THREAD";
        case CUDA_ERROR_TIMEOUT:
            return "CUDA_ERROR_TIMEOUT";
        case CUDA_ERROR_GRAPH_EXEC_UPDATE_FAILURE:
            return "CUDA_ERROR_GRAPH_EXEC_UPDATE_FAILURE";
        case CUDA_ERROR_EXTERNAL_DEVICE:
            return "CUDA_ERROR_EXTERNAL_DEVICE";
        case CUDA_ERROR_INVALID_CLUSTER_SIZE:
            return "CUDA_ERROR_INVALID_CLUSTER_SIZE";
        case CUDA_ERROR_FUNCTION_NOT_LOADED:
            return "CUDA_ERROR_FUNCTION_NOT_LOADED";
        case CUDA_ERROR_INVALID_RESOURCE_TYPE:
            return "CUDA_ERROR_INVALID_RESOURCE_TYPE";
        case CUDA_ERROR_INVALID_RESOURCE_CONFIGURATION:
            return "CUDA_ERROR_INVALID_RESOURCE_CONFIGURATION";
        case CUDA_ERROR_KEY_ROTATION:
            return "CUDA_ERROR_KEY_ROTATION";
        case CUDA_ERROR_STREAM_DETACHED:
            return "CUDA_ERROR_STREAM_DETACHED";
        case CUDA_ERROR_GRAPH_RECAPTURE_FAILURE:
            return "CUDA_ERROR_GRAPH_RECAPTURE_FAILURE";
        case CUDA_ERROR_UNKNOWN:
            return "CUDA_ERROR_UNKNOWN";
        default:
            return "Unknown error";
    }
}

std::string ToString(nvJitLinkResult err) {
    switch (err) {
        case NVJITLINK_SUCCESS:
            return "NVJITLINK_SUCCESS";
        case NVJITLINK_ERROR_UNRECOGNIZED_OPTION:
            return "NVJITLINK_ERROR_UNRECOGNIZED_OPTION";
        case NVJITLINK_ERROR_MISSING_ARCH:
            return "NVJITLINK_ERROR_MISSING_ARCH";
        case NVJITLINK_ERROR_INVALID_INPUT:
            return "NVJITLINK_ERROR_INVALID_INPUT";
        case NVJITLINK_ERROR_PTX_COMPILE:
            return "NVJITLINK_ERROR_PTX_COMPILE";
        case NVJITLINK_ERROR_NVVM_COMPILE:
            return "NVJITLINK_ERROR_NVVM_COMPILE";
        case NVJITLINK_ERROR_INTERNAL:
            return "NVJITLINK_ERROR_INTERNAL";
        case NVJITLINK_ERROR_THREADPOOL:
            return "NVJITLINK_ERROR_THREADPOOL";
        case NVJITLINK_ERROR_UNRECOGNIZED_INPUT:
            return "NVJITLINK_ERROR_UNRECOGNIZED_INPUT";
        case NVJITLINK_ERROR_FINALIZE:
            return "NVJITLINK_ERROR_FINALIZE";
        case NVJITLINK_ERROR_NULL_INPUT:
            return "NVJITLINK_ERROR_NULL_INPUT";
        case NVJITLINK_ERROR_INCOMPATIBLE_OPTIONS:
            return "NVJITLINK_ERROR_INCOMPATIBLE_OPTIONS";
        case NVJITLINK_ERROR_INCORRECT_INPUT_TYPE:
            return "NVJITLINK_ERROR_INCORRECT_INPUT_TYPE";
        case NVJITLINK_ERROR_ARCH_MISMATCH:
            return "NVJITLINK_ERROR_ARCH_MISMATCH";
        case NVJITLINK_ERROR_OUTDATED_LIBRARY:
            return "NVJITLINK_ERROR_OUTDATED_LIBRARY";
        case NVJITLINK_ERROR_MISSING_FATBIN:
            return "NVJITLINK_ERROR_MISSING_FATBIN";
        case NVJITLINK_ERROR_UNRECOGNIZED_ARCH:
            return "NVJITLINK_ERROR_UNRECOGNIZED_ARCH";
        case NVJITLINK_ERROR_UNSUPPORTED_ARCH:
            return "NVJITLINK_ERROR_UNSUPPORTED_ARCH";
        case NVJITLINK_ERROR_LTO_NOT_ENABLED:
            return "NVJITLINK_ERROR_LTO_NOT_ENABLED";
        default:
            return "Unknown error";
    }
}
}// namespace HUH