#include <HUH/Window/prototypes/window_proto.h>

namespace HUH {

std::string ToString(KeyBindings key) {
    switch (key) {
        case KeyBindings::Unknown:
            return "Unknown";
        case KeyBindings::A:
            return "A";
        case KeyBindings::B:
            return "B";
        case KeyBindings::C:
            return "C";
        case KeyBindings::D:
            return "D";
        case KeyBindings::E:
            return "E";
        case KeyBindings::F:
            return "F";
        case KeyBindings::G:
            return "G";
        case KeyBindings::H:
            return "H";
        case KeyBindings::I:
            return "I";
        case KeyBindings::J:
            return "J";
        case KeyBindings::K:
            return "K";
        case KeyBindings::L:
            return "L";
        case KeyBindings::M:
            return "M";
        case KeyBindings::N:
            return "N";
        case KeyBindings::O:
            return "O";
        case KeyBindings::P:
            return "P";
        case KeyBindings::Q:
            return "Q";
        case KeyBindings::R:
            return "R";
        case KeyBindings::S:
            return "S";
        case KeyBindings::T:
            return "T";
        case KeyBindings::U:
            return "U";
        case KeyBindings::V:
            return "V";
        case KeyBindings::W:
            return "W";
        case KeyBindings::X:
            return "X";
        case KeyBindings::Y:
            return "Y";
        case KeyBindings::Z:
            return "Z";
        case KeyBindings::a:
            return "a";
        case KeyBindings::b:
            return "b";
        case KeyBindings::c:
            return "c";
        case KeyBindings::d:
            return "d";
        case KeyBindings::e:
            return "e";
        case KeyBindings::f:
            return "f";
        case KeyBindings::g:
            return "g";
        case KeyBindings::h:
            return "h";
        case KeyBindings::i:
            return "i";
        case KeyBindings::j:
            return "j";
        case KeyBindings::k:
            return "k";
        case KeyBindings::l:
            return "l";
        case KeyBindings::m:
            return "m";
        case KeyBindings::n:
            return "n";
        case KeyBindings::o:
            return "o";
        case KeyBindings::p:
            return "p";
        case KeyBindings::q:
            return "q";
        case KeyBindings::r:
            return "r";
        case KeyBindings::s:
            return "s";
        case KeyBindings::t:
            return "t";
        case KeyBindings::u:
            return "u";
        case KeyBindings::v:
            return "v";
        case KeyBindings::w:
            return "w";
        case KeyBindings::x:
            return "x";
        case KeyBindings::y:
            return "y";
        case KeyBindings::z:
            return "z";
        case KeyBindings::Mouse_1:
            return "Mouse_1";
        case KeyBindings::Mouse_2:
            return "Mouse_2";
        case KeyBindings::Mouse_3:
            return "Mouse_3";
        case KeyBindings::Mouse_4:
            return "Mouse_4";
        case KeyBindings::Mouse_5:
            return "Mouse_5";
        case KeyBindings::LeftArrow:
            return "LeftArrow";
        case KeyBindings::RightArrow:
            return "RightArrow";
        case KeyBindings::UpperArrow:
            return "UpperArrow";
        case KeyBindings::DownArrow:
            return "DownArrow";
        case KeyBindings::Shift:
            return "Shift";
        case KeyBindings::Control:
            return "Control";
        case KeyBindings::Other:
            return "Other";
        default:
            return "Unknown";
    }
}
}// namespace HUH