#include <HUH/Window/prototypes/window_proto.h>

namespace HUH {

std::string ToString(KeyBindings key) {
    switch (key) {
        case KeyBindings::Unknown:
            return "Unknown";
        case KeyBindings::A:
            return "A";
        case KeyBindings::B:
            return "B";
        case KeyBindings::C:
            return "C";
        case KeyBindings::D:
            return "D";
        case KeyBindings::E:
            return "E";
        case KeyBindings::F:
            return "F";
        case KeyBindings::G:
            return "G";
        case KeyBindings::H:
            return "H";
        case KeyBindings::I:
            return "I";
        case KeyBindings::J:
            return "J";
        case KeyBindings::K:
            return "K";
        case KeyBindings::L:
            return "L";
        case KeyBindings::M:
            return "M";
        case KeyBindings::N:
            return "N";
        case KeyBindings::O:
            return "O";
        case KeyBindings::P:
            return "P";
        case KeyBindings::Q:
            return "Q";
        case KeyBindings::R:
            return "R";
        case KeyBindings::S:
            return "S";
        case KeyBindings::T:
            return "T";
        case KeyBindings::U:
            return "U";
        case KeyBindings::V:
            return "V";
        case KeyBindings::W:
            return "W";
        case KeyBindings::X:
            return "X";
        case KeyBindings::Y:
            return "Y";
        case KeyBindings::Z:
            return "Z";
        case KeyBindings::a:
            return "a";
        case KeyBindings::b:
            return "b";
        case KeyBindings::c:
            return "c";
        case KeyBindings::d:
            return "d";
        case KeyBindings::e:
            return "e";
        case KeyBindings::f:
            return "f";
        case KeyBindings::g:
            return "g";
        case KeyBindings::h:
            return "h";
        case KeyBindings::i:
            return "i";
        case KeyBindings::j:
            return "j";
        case KeyBindings::k:
            return "k";
        case KeyBindings::l:
            return "l";
        case KeyBindings::m:
            return "m";
        case KeyBindings::n:
            return "n";
        case KeyBindings::o:
            return "o";
        case KeyBindings::p:
            return "p";
        case KeyBindings::q:
            return "q";
        case KeyBindings::r:
            return "r";
        case KeyBindings::s:
            return "s";
        case KeyBindings::t:
            return "t";
        case KeyBindings::u:
            return "u";
        case KeyBindings::v:
            return "v";
        case KeyBindings::w:
            return "w";
        case KeyBindings::x:
            return "x";
        case KeyBindings::y:
            return "y";
        case KeyBindings::z:
            return "z";
        case KeyBindings::N0:
            return "N0";
        case KeyBindings::N1:
            return "N1";
        case KeyBindings::N2:
            return "N2";
        case KeyBindings::N3:
            return "N3";
        case KeyBindings::N4:
            return "N4";
        case KeyBindings::N5:
            return "N5";
        case KeyBindings::N6:
            return "N6";
        case KeyBindings::N7:
            return "N7";
        case KeyBindings::N8:
            return "N8";
        case KeyBindings::N9:
            return "N9";
        case KeyBindings::KP0:
            return "KP0";
        case KeyBindings::KP1:
            return "KP1";
        case KeyBindings::KP2:
            return "KP2";
        case KeyBindings::KP3:
            return "KP3";
        case KeyBindings::KP4:
            return "KP4";
        case KeyBindings::KP5:
            return "KP5";
        case KeyBindings::KP6:
            return "KP6";
        case KeyBindings::KP7:
            return "KP7";
        case KeyBindings::KP8:
            return "KP8";
        case KeyBindings::KP9:
            return "KP9";
        case KeyBindings::F1:
            return "F1";
        case KeyBindings::F2:
            return "F2";
        case KeyBindings::F3:
            return "F3";
        case KeyBindings::F4:
            return "F4";
        case KeyBindings::F5:
            return "F5";
        case KeyBindings::F6:
            return "F6";
        case KeyBindings::F7:
            return "F7";
        case KeyBindings::F8:
            return "F8";
        case KeyBindings::F9:
            return "F9";
        case KeyBindings::F10:
            return "F10";
        case KeyBindings::F11:
            return "F11";
        case KeyBindings::F12:
            return "F12";
        case KeyBindings::F13:
            return "F13";
        case KeyBindings::F14:
            return "F14";
        case KeyBindings::F15:
            return "F15";
        case KeyBindings::F16:
            return "F16";
        case KeyBindings::F17:
            return "F17";
        case KeyBindings::F18:
            return "F18";
        case KeyBindings::F19:
            return "F19";
        case KeyBindings::F20:
            return "F20";
        case KeyBindings::F21:
            return "F21";
        case KeyBindings::F22:
            return "F22";
        case KeyBindings::F23:
            return "F23";
        case KeyBindings::F24:
            return "F24";
        case KeyBindings::Mouse_1:
            return "Mouse_1";
        case KeyBindings::Mouse_2:
            return "Mouse_2";
        case KeyBindings::Mouse_3:
            return "Mouse_3";
        case KeyBindings::Mouse_4:
            return "Mouse_4";
        case KeyBindings::Mouse_5:
            return "Mouse_5";
        case KeyBindings::ArrowLeft:
            return "ArrowLeft";
        case KeyBindings::ArrowRight:
            return "ArrowRight";
        case KeyBindings::ArrowUp:
            return "ArrowUp";
        case KeyBindings::ArrowDown:
            return "ArrowDown";
        case KeyBindings::Escape:
            return "Escape";
        case KeyBindings::LeftControl:
            return "LeftControl";
        case KeyBindings::RightControl:
            return "RightControl";
        case KeyBindings::LeftShift:
            return "LeftShift";
        case KeyBindings::RightShift:
            return "RightShift";
        case KeyBindings::LeftAlt:
            return "LeftAlt";
        case KeyBindings::RightAlt:
            return "RightAlt";
        case KeyBindings::BackSpace:
            return "BackSpace";
        case KeyBindings::Enter:
            return "Enter";
        case KeyBindings::Tab:
            return "Tab";
        case KeyBindings::Other:
            return "Other";
        default:
            return "Unknown";
    }
}
}// namespace HUH