function(huh_add_compile_options)
    set(multiValueArgs GCClang Intel MSVC)
    cmake_parse_arguments(PARSE_ARGV 0 Compile_Option_For "" "" "${multiValueArgs}")

    if ((CMAKE_CXX_COMPILER_ID MATCHES "GNU") OR (CMAKE_CXX_COMPILER_ID MATCHES "Clang"))
        if (Compile_Option_For_GCClang)
            message(STATUS "Compile options set for GCC or Clang ${Compile_Option_For_GCClang}")
            add_compile_options(${Compile_Option_For_GCClang})
        endif ()
    elseif (CMAKE_CXX_COMPILER_ID MATCHES "Intel")
        if (Compile_Option_For_Intel)
            message(STATUS "Compile options set for Intel ${Compile_Option_For_Intel}")
            add_compile_options(${Compile_Option_For_Intel})
        endif ()
    elseif (CMAKE_CXX_COMPILER_ID MATCHES "MSVC")
        if (Compile_Option_For_MSVC)
            message(STATUS "Compile options set for Intel ${Compile_Option_For_MSVC}")
            add_compile_options(${Compile_Option_For_MSVC})
        endif ()
    endif ()
endfunction()

function(huh_target_compile_options Target Visibility)
    set(multiValueArgs GCClang Intel MSVC)
    cmake_parse_arguments(PARSE_ARGV 0 Compile_Option_For "" "" "${multiValueArgs}")

    if ((CMAKE_CXX_COMPILER_ID MATCHES "GNU") OR (CMAKE_CXX_COMPILER_ID MATCHES "Clang"))
        if (Compile_Option_For_GCClang)
            message(STATUS "Compile options set for GCC or Clang ${Compile_Option_For_GCClang}")
            target_compile_options(${Target} ${Visibility} ${Compile_Option_For_GCClang})
        endif ()
    elseif (CMAKE_CXX_COMPILER_ID MATCHES "Intel")
        if (Compile_Option_For_Intel)
            message(STATUS "Compile options set for Intel ${Compile_Option_For_Intel}")
            target_compile_options(${Target} ${Visibility} ${Compile_Option_For_Intel})
        endif ()
    elseif (CMAKE_CXX_COMPILER_ID MATCHES "MSVC")
        if (Compile_Option_For_MSVC)
            message(STATUS "Compile options set for Intel ${Compile_Option_For_MSVC}")
            target_compile_options(${Target} ${Visibility} ${Compile_Option_For_MSVC})
        endif ()
    endif ()
endfunction()
