function(huh_add_module_build Target Visibility Module)
    get_property(tmp TARGET ${Target} PROPERTY ${Module}_DEPENDENCY)
    get_property(Build_Modules TARGET ${Target} PROPERTY BUILD_MODULES)
    foreach (Dependency IN LISTS tmp)
        if (NOT Build_Modules)
            huh_add_module_build(${Target} ${Visibility} ${Dependency})
        else ()
            string(REPLACE "_" "/" Dependency_Path ${Dependency})
            list(FIND Build_Modules modules/${Dependency_Path} Found)
            if (${Found} EQUAL -1)
                huh_add_module_build(${Target} ${Visibility} ${Dependency})
            endif ()
        endif ()
    endforeach ()
    if (NOT Build_Modules)
        string(REPLACE "_" "/" Module_Path ${Module})
        set_property(TARGET ${Target} APPEND PROPERTY BUILD_MODULES modules/${Module_Path})
        string(TOUPPER HUH_USE_${Module} MODULE_COMPILE_DEF)
        target_compile_definitions(${Target} ${Visibility} ${MODULE_COMPILE_DEF})
    else ()
        string(REPLACE "_" "/" Module_Path ${Module})
        list(FIND Build_Modules modules/${Module_Path} Found)
        if (${Found} EQUAL -1)
            set_property(TARGET ${Target} APPEND PROPERTY BUILD_MODULES modules/${Module_Path})
            string(TOUPPER HUH_USE_${Module} MODULE_COMPILE_DEF)
            target_compile_definitions(${Target} ${Visibility} ${MODULE_COMPILE_DEF})
        endif ()
    endif ()
endfunction()

function(huh_set_modules_dependency Target)
    set_property(TARGET ${Target} APPEND PROPERTY Array_DEPENDENCY Threading)
    set_property(TARGET ${Target} APPEND PROPERTY RHI_DEPENDENCY VulkanLoader Math FileHandling_Image)
    set_property(TARGET ${Target} APPEND PROPERTY Window_DEPENDENCY Math)
    set_property(TARGET ${Target} APPEND PROPERTY Graphics_Camera_DEPENDENCY Math RHI Window)
    set_property(TARGET ${Target} APPEND PROPERTY FileHandling_Image_DEPENDENCY Math)
    if (HUH_LINUX)
        set_property(TARGET ${Target} APPEND PROPERTY Window_DEPENDENCY WaylandConnector)
    endif ()
endfunction()

