function(huh_add_module_build Target Visibility Module)
    get_property(tmp TARGET ${Target} PROPERTY ${Module}_DEPENDENCY)
    get_property(Build_Modules TARGET ${Target} PROPERTY BUILD_MODULES)
    foreach (Dependency IN LISTS tmp)
        if (NOT Build_Modules)
            huh_add_module_build(${Target} ${Visibility} ${Dependency})
        else ()
            list(FIND Build_Modules modules/${Dependency} Found)
            if (${Found} EQUAL -1)
                huh_add_module_build(${Target} ${Visibility} ${Dependency})
            endif ()
        endif ()
    endforeach ()
    if (NOT Build_Modules)
        set_property(TARGET ${Target} APPEND PROPERTY BUILD_MODULES modules/${Module})
        string(TOUPPER HUH_USE_${Module} MODULE_COMPILE_DEF)
        target_compile_definitions(${Target} ${Visibility} ${MODULE_COMPILE_DEF})
    else ()
        list(FIND Build_Modules modules/${Module} Found)
        if (${Found} EQUAL -1)
            set_property(TARGET ${Target} APPEND PROPERTY BUILD_MODULES modules/${Module})
            string(TOUPPER HUH_USE_${Module} MODULE_COMPILE_DEF)
            target_compile_definitions(${Target} ${Visibility} ${MODULE_COMPILE_DEF})
        endif ()
    endif ()
endfunction()

function(huh_set_modules_dependency Target)
    set_property(TARGET ${Target} APPEND PROPERTY Array_DEPENDENCY Threading)
    set_property(TARGET ${Target} APPEND PROPERTY RHI_DEPENDENCY VulkanLoader Math)
    set_property(TARGET ${Target} APPEND PROPERTY Window_DEPENDENCY Math)
    if (HUH_LINUX)
        set_property(TARGET ${Target} APPEND PROPERTY Window_DEPENDENCY WaylandConnector)
    endif ()
endfunction()

