function(huh_add_module_build Target Module)
    get_property(tmp TARGET ${Target} PROPERTY ${Module}_DEPENDENCY)
    get_property(Build_Modules TARGET ${Target} PROPERTY BUILD_MODULES)
    foreach (Dependency IN LISTS tmp)
        if (NOT Build_Modules)
            huh_add_module_build(${Target} ${Dependency})
        else ()
            list(FIND Build_Modules modules/${Dependency} Found)
            if (${Found} EQUAL -1)
                huh_add_module_build(${Target} ${Dependency})
            endif ()
        endif ()
    endforeach ()
    if (NOT Build_Modules)
        set_property(TARGET ${Target} APPEND PROPERTY BUILD_MODULES modules/${Module})
    else ()
        list(FIND Build_Modules modules/${Module} Found)
        if (${Found} EQUAL -1)
            set_property(TARGET ${Target} APPEND PROPERTY BUILD_MODULES modules/${Module})
        endif ()
    endif ()


endfunction()

function(huh_set_modules_dependency Target)
    set_property(TARGET ${Target} PROPERTY Array_DEPENDENCY Threading)
endfunction()

